# Generated by Django 3.0.5 on 2020-05-26 18:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userext',
            name='activation_link',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
